### ISSUE TITLE
Direct message deleting. 

### ISSUE THREAD

**Issue by jaison10** [kfei/slack-cleaner#88]
# Delete all messages from a direct message channel
slack-cleaner --token <TOKEN> --message --direct sherry --user johndoe

What's sherry and johndoe here?

**Comment by sgratzl** [comment]
this project is not maintained anymore, my fork is: https://github.com/sgratzl/slack-cleaner

re user names, you can use `--info` in the forked version which should list a list of users. 

Note: due to Slack API restrictions, deleting direct messages is not fully supported. One can just deleted the direct messages send by the owner of the token. It is not possible to delete the message of the opposite side.
